version: '3'
services:
  serviceone:
    image: service-one
    ports:
      - "8080:8080"
  servicetwo:
    image: service-two
    deploy:
      replicas: 2 # This service is scaled to 5 replicas
    ports:
      - "8090:8090"
  custom-proxy:
    build: .
    ports:
      - "80:80"
    depends_on:
      - serviceone
      - servicetwo